version: '3.4'

services:
    jaeger:
        image: jaegertracing/all-in-one
        container_name: jaeger
        hostname: jaeger
        restart: always
        ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"
    db:
        image: "mcr.microsoft.com/mssql/server"

    rabbitmq:
        image: rabbitmq:3-management
        hostname: my-rabbit
        volumes:
            - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
            - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
            - ./rabbitmq/logs:/var/log/rabbitmq/log
        ports:
            - 5672:5672
            - 15672:15672